import { defineField, defineType } from "sanity";
export const siteSettings = defineType({
  name: "siteSettings",
  title: "Configuración del sitio",
  type: "document",
  fields: [
    defineField({
      name: "name",
      title: "Nombre legal",
      description: "Nombre oficial de la empresa.",
      type: "string",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "primaryLogo",
      title: "Logo principal",
      description: "Logo utilizado sobre fondos claros.",
      type: "image",
      options: { hotspot: true },
    }),
    defineField({
      name: "alternateLogo",
      title: "Logo alternativo",
      description: "Logo para fondos oscuros u otros contextos.",
      type: "image",
      options: { hotspot: true },
    }),
    defineField({
      name: "favicon",
      title: "Favicon",
      description: "Ícono pequeño del navegador.",
      type: "image",
    }),
    defineField({
      name: "colors",
      title: "Colores de marca",
      description: "Valores hexadecimales aprobados para el sitio.",
      type: "object",
      fields: [
        { name: "primary", title: "Primario", type: "string" },
        { name: "secondary", title: "Secundario", type: "string" },
        { name: "accent", title: "Acento", type: "string" },
      ],
    }),
    defineField({
      name: "phone",
      title: "Teléfono",
      description: "Teléfono público principal.",
      type: "string",
    }),
    defineField({
      name: "email",
      title: "Correo general",
      description: "Correo público de información.",
      type: "string",
    }),
    defineField({
      name: "contactRecipient",
      title: "Correo receptor de formularios",
      description: "Destino interno; no se muestra públicamente.",
      type: "string",
    }),
    defineField({
      name: "address",
      title: "Dirección",
      description: "Dirección postal pública.",
      type: "text",
      rows: 3,
    }),
    defineField({
      name: "hours",
      title: "Horario",
      description: "Días y horas de atención.",
      type: "text",
      rows: 3,
    }),
    defineField({
      name: "socialLinks",
      title: "Redes sociales",
      description: "Perfiles públicos aprobados.",
      type: "array",
      of: [{ type: "reference", to: [{ type: "socialLink" }] }],
    }),
    defineField({
      name: "footer",
      title: "Texto del pie de página",
      description: "Texto institucional breve del footer.",
      type: "text",
      rows: 3,
    }),
    defineField({
      name: "globalSeo",
      title: "SEO global",
      description: "Valores predeterminados para buscadores.",
      type: "object",
      fields: [
        { name: "title", title: "Título", type: "string" },
        { name: "description", title: "Descripción", type: "text" },
        { name: "image", title: "Imagen social", type: "image" },
      ],
    }),
    defineField({
      name: "domain",
      title: "Dominio",
      description: "Dominio canónico, incluyendo https://.",
      type: "url",
    }),
    defineField({
      name: "analyticsId",
      title: "Identificador de analítica",
      description: "Identificador público; no introduzca secretos.",
      type: "string",
    }),
    defineField({
      name: "dataReviewedAt",
      title: "Fecha de revisión de datos",
      description: "Última fecha en que se verificaron los datos corporativos.",
      type: "date",
    }),
  ],
});
